version: '3'
services:    
     

  postgresnode:
    image: postgresnode    
    build: ./postgresnode
    container_name: postgresnode
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=marketplace
      - POSTGRES_PASSWORD=marketplace
      - POSTGRES_USER=postgres
    networks:
      - pnet
    volumes:
      - ./../data/postgresone/logs/:/opt/postgres/logs
      - ./../data/postgresone/data:/var/lib/postgresql/data
      - ./postgresnode/postgresql.conf:/etc/postgresql/postgresql.conf:rw   
    sysctls:
      - kernel.shmmax=100663296

  account:
    image: account
    build: ./account
    container_name: account
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:
      - postgresnode         
    depends_on:
      - postgresnode          
    ports:
      - '4040:4040'   
    networks:
      - pnet
      
  profile:
    image: profile
    build: ./profile
    container_name: profile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:
      - postgresnode         
    depends_on:
      - postgresnode          
    ports:
      - '5050:5050'   
    networks:
      - pnet     
      
  loan:
    image: loan
    build: ./loan
    container_name: loan
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:
      - postgresnode         
    depends_on:
      - postgresnode          
    ports:
      - '6060:6060'   
    networks:
      - pnet 
      
      
      
      
  
networks:
  pnet:
    driver: bridge   
    ipam:
      driver: default
      