management:
  endpoint:    
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     base-path: /management
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'
      
server:
    http2:
     enabled: true
    port: 6060
    servlet:
      session:
        timeout: 600s
    undertow:
      buffer-size: 40960
      no-request-timeout: 5000
      threads:
        io: 1200
        worker: 1200
    compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
      min-response-size: 1024


    
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS:  false
    
  application:
    name: loan
    
  profiles:
    active:
      default
     
  cloud:
    discovery:
       service-id: loan
       enabled: true



  datasource:
    hikari:
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1800000
        auto-commit: false
    tomcat:
      initial-size: 50
      max-wait: 80000
      max-active: 600
      max-idle: 100
      min-idle: 30
      removeAbandoned: true
      removeAbandonedTimeout: 800
      timeBetweenEvictionRunsMillis: 3400000
      minEvictableIdleTimeMillis: 5500000
      default-auto-commit: false  
    url:  jdbc:postgresql://postgresnode:5432/marketplace
    username: postgres
    password: marketplace  
    platform: POSTGRESQL
    testWhileIdle: true
    validationQuery: SELECT 1
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database: postgresql  
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
    properties: 
      hibernate:
       connection:
        provider_disables_autocommit: false
       temp:
        use_jdbc_metadata_defaults: false 


logging:
    level:
      root: INFO
      com.lending.app: INFO
